# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 01:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador_pedido', models.CharField(blank=True, max_length=50)),
                ('numero_guiavm', models.CharField(blank=True, max_length=50)),
                ('numero_guia', models.CharField(max_length=50)),
                ('nombre_cliente', models.CharField(max_length=100)),
                ('descripcion_corta_pedido', models.CharField(blank=True, max_length=100)),
                ('descripcion_larga_pedido', models.TextField()),
                ('deseo_borrar', models.BooleanField(default=False)),
                ('estado_pedido', models.CharField(choices=[('PAGADO', 'Pagado'), ('PENDIENTE', 'Pago Pendiente'), ('RESERVADO', 'Reservado'), ('DESPACHABLE', 'Listo para despachar'), ('ENTREGABLE', 'Listo para entregar')], default='PENDIENTE', max_length=50)),
                ('fecha_entrega_pedido', models.DateField()),
                ('hora_entrega_pedido', models.TimeField()),
                ('direccion_entrega_pedido', models.CharField(blank=True, max_length=150)),
                ('sucursal_entrega_pedido', models.CharField(choices=[('VICUNA', 'Vicuna Mackenna'), ('MIRADOR', 'Mirador Azul'), ('TOBALABA', 'Tobalaba'), ('DOMICILIO', 'Domicilio')], default='VICUNA', max_length=50)),
                ('abono_pedido', models.CharField(max_length=12)),
                ('precio_total_pedido', models.CharField(max_length=12)),
                ('metodo_pago_pedido', models.CharField(choices=[('TRANSFERENCIA', 'Transferencia electronica'), ('EFECTIVO', 'Efectivo'), ('CHEQUE', 'Cheque'), ('CREDITO', 'Tarjeta de Credito'), ('OTRO', 'Otro metodo')], default='TRANSFERENCIA', max_length=50)),
                ('celular_cliente', models.CharField(blank=True, max_length=12)),
                ('telefono_cliente', models.CharField(blank=True, max_length=12)),
                ('correo_cliente', models.EmailField(blank=True, max_length=254)),
                ('fecha_creacion_pedido', models.DateTimeField(auto_now_add=True)),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
